version: '3.0'

services:
  db:
    image: postgres
    ports:
      - '5431:5432'
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db